apiVersion: apps/v1
kind: Deployment
metadata:
  name: deguzman-auth
  namespace: deguzman-auth
  labels:
    app: deguzman-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deguzman-auth
  template:
    metadata:
      labels:
        app: deguzman-auth
    spec:
      containers:
        - name: deguzman-auth
          image: matthew10125/deguzman-auth:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: deguzman-auth-port
          envFrom:
            - secretRef:
                name: env
