apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deguzman-auth-ingress
  namespace: deguzman-auth
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - auth.deguzman.cloud
    secretName: auth-tls
  rules:
  - host: auth.deguzman.cloud
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: deguzman-auth
              port:
                number: 80
