apiVersion: v1
kind: Service
metadata:
  name: deguzman-auth
  namespace: deguzman-auth
  labels:
    app: deguzman-auth
spec:
  selector:
    app: deguzman-auth
  ports:
    - port: 80
      targetPort: deguzman-auth-port
  type: ClusterIP
