apiVersion: v1
kind: Service
metadata:
  name: auth-frontend
  namespace: deguzman-auth
  labels:
    app: auth-frontend
spec:
  selector:
    app: auth-frontend
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
