apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: boshi
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api-boshi.deguzman.cloud
    - dev-api-boshi.deguzman.cloud
    secretName: boshi-tls
  rules:
  - host: api-boshi.deguzman.cloud
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: boshi-backend
              port:
                number: 80
  - host: dev-api-boshi.deguzman.cloud
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: boshi-backend
              port:
                number: 80
