apiVersion: apps/v1
kind: Deployment
metadata:
  name: boshi-backend
  namespace: boshi
  labels:
    app: boshi-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: boshi-backend
  template:
    metadata:
      labels:
        app: boshi-backend
    spec:
      containers:
      - name: boshi-backend
        image: matthew10125/boshi-backend:latest
        imagePullPolicy: Always
        env:
        - name: PORT
          value: "80"
        ports:
          - containerPort: 80
