apiVersion: v1
kind: Service
metadata:
  name: boshi-backend
  namespace: boshi
  labels:
    app: boshi-backend
spec:
  selector:
    app: boshi-backend
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
