apiVersion: apps/v1
kind: Deployment
metadata:
  name: qrcode-backend
  namespace: qrcode
  labels:
    app: qrcode-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qrcode-backend
  template:
    metadata:
      labels:
        app: qrcode-backend
    spec:
      containers:
        - name: qrcode-backend
          image: matthew10125/qrcode-backend
          imagePullPolicy: Always
          volumeMounts:
          - name: qrcode-data
            mountPath: /srv/qrcode
          ports:
            - containerPort: 80
              name: backend-port
      nodeName: lois
      volumes:
      - name: qrcode-data
        persistentVolumeClaim:
          claimName: qrcode-pvc
