apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-backend
  namespace: deguzman-auth
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: auth-backend
          image: matthew10125/deguzman-auth-backend:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              value: postgresql://admin:password@example.com:5432/db
            - name: BASE_URL
              value: example.com
            - name: ENV
              value: DEV
            - name: SMTP_FROM
              value: from@example.com
            - name: SMTP_HOST
              value: mail.example.com
            - name: SMTP_PORT
              value: 587
            - name: SMTP_USERNAME
              value: user
            - name: SMTP_PASSWORD
              value: password
          ports:
            - containerPort: 80
