apiVersion: v1
kind: Service
metadata:
  name: auth-backend
  namespace: deguzman-auth
  labels:
    app: auth-backend
spec:
  selector:
    app: auth-backend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
