apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qrcode-ingress
  namespace: qrcode
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - qr.deguzman.cloud
    secretName: qrcode-tls
  rules:
  - host: qr.deguzman.cloud
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: qrcode-frontend
              port:
                number: 80
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: qrcode-backend
              port:
                number: 80
