apiVersion: v1
kind: Service
metadata:
  name: qrcode-frontend
  labels:
    app: qrcode-frontend
spec:
  selector:
    app: qrcode-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
