apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kube-deploy-ingress
  namespace: kube-deploy
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - k8s.deguzman.cloud
    secretName: kube-deploy-tls
  rules:
  - host: k8s.deguzman.cloud
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: kube-deploy
              port:
                number: 80
