apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgc-backend
  namespace: dgc
  labels:
    app: dgc-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dgc-backend
  template:
    metadata:
      labels:
        app: dgc-backend
    spec:
      serviceAccountName: client-service-account
      containers:
      - name: dgc-backend
        image: matthew10125/dgc-backend:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        envFrom:
        - secretRef:
            name: backend-secrets
