apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dgc-ingress
  namespace: dgc
  annotations:
    #nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - deguzman.cloud
    secretName: dgc-tls
  rules:
  - host: deguzman.cloud
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: dgc-frontend-svc
              port:
                number: 80
