apiVersion: v1
kind: Service
metadata:
  name: dgc-frontend-svc
  namespace: dgc
  labels:
    app: dgc-frontend
spec:
  selector:
    app: dgc-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
