# https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  # Minecraft
  25565: "minecraft/minecraft:25565"

  # Docker Mailserver
  25: "mailserver/mailserver:25::PROXY"
  465: "mailserver/mailserver:465::PROXY"
  587: "mailserver/mailserver:587::PROXY"
  993: "mailserver/mailserver:993::PROXY"


