apiVersion: v1
kind: Service
metadata:
  name: dsa-frontend
  namespace: dsa
  labels:
    app: dsa-frontend
spec:
  selector:
    app: dsa-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
