apiVersion: v1
kind: Service
metadata:
  name: ghost-service
  namespace: ghost
  labels:
    app: ghost-service
spec:
  selector:
    app: ghost
  ports:
    - port: 2368
      targetPort: 2368
  type: ClusterIP
